name: Simple Docker Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build using Docker
      run: |
        # 直接使用docker run编译，不需要构建镜像
        docker run --rm -v $(pwd):/workdir -w /workdir ubuntu:16.04 bash -c "
          apt-get update && \
          apt-get install -y gcc-arm-linux-gnueabi gcc-arm-linux-gnueabihf gcc-mips-linux-gnu && \
          arm-linux-gnueabi-gcc -O2 -marm ptbl.c -ldl -o ptbl -Wl,--export-dynamic && \
          arm-linux-gnueabihf-gcc -O2 -marm ptbl.c -ldl -o ptbl_hf -Wl,--export-dynamic && \
          mips-linux-gnu-gcc -O2 ptbl.c -ldl -o ptbl_mips -Wl,--export-dynamic
        "

    - name: Verify binaries
      run: |
        echo "Compilation completed!"
        ls -la ptbl*
        echo "Binary info:"
        file ptbl* 2>/dev/null || echo "Could not check file info"

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: cross-compiled-binaries
        path: |
          ptbl
          ptbl_hf
          ptbl_mips
