name: Build Cross-Platform Tool

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [arm, arm-hf, mips]
        include:
          - target: arm
            cc: arm-linux-gnueabi-gcc
            output: ptbl
            flags: -marm
          - target: arm-hf
            cc: arm-linux-gnueabihf-gcc
            output: ptbl_hf
            flags: -marm
          - target: mips
            cc: mips-linux-gnu-gcc
            output: ptbl_mips
            flags: ""

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install toolchains
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc-arm-linux-gnueabi \
          gcc-arm-linux-gnueabihf \
          gcc-mips-linux-gnu

    - name: Build ${{ matrix.target }}
      run: |
        ${{ matrix.cc }} -O2 -Wall ${{ matrix.flags }} ptbl.c -ldl -o ${{ matrix.output }} -Wl,--export-dynamic
        echo "Binary info:"
        file ${{ matrix.output }}

    - name: Upload ${{ matrix.target }} binary
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}-binary
        path: ${{ matrix.output }}
