name: Build for GLIBC 2.26

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04  # Ubuntu 18.04 自带 GLIBC 2.27，接近目标版本
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install toolchains
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc-arm-linux-gnueabi \
          gcc-arm-linux-gnueabihf \
          gcc-mips-linux-gnu

    - name: Build with compatibility flags
      run: |
        # 添加兼容性标志
        arm-linux-gnueabi-gcc -O2 -marm -Wall ptbl.c -ldl -o ptbl -Wl,--export-dynamic
        arm-linux-gnueabihf-gcc -O2 -marm -Wall ptbl.c -ldl -o ptbl_hf -Wl,--export-dynamic
        mips-linux-gnu-gcc -O2 -Wall ptbl.c -ldl -o ptbl_mips -Wl,--export-dynamic

    - name: Check GLIBC requirements
      run: |
        echo "Checking GLIBC dependencies:"
        objdump -T ptbl | grep GLIBC | sort -u || true
        objdump -T ptbl_hf | grep GLIBC | sort -u || true
        objdump -T ptbl_mips | grep GLIBC | sort -u || true

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: glibc-2.26-compatible-binaries
        path: |
          ptbl
          ptbl_hf
          ptbl_mips
