name: Build Cross-Platform Tool

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [arm-linux-gnueabi, arm-linux-gnueabihf, mips-unknown-linux-uclibc]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install cross-compilation toolchains
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc-arm-linux-gnueabi \
          g++-arm-linux-gnueabi \
          gcc-arm-linux-gnueabihf \
          g++-arm-linux-gnueabihf \
          gcc-mips-linux-gnu \
          g++-mips-linux-gnu \
          binutils-mips-linux-gnu

    - name: Build for ${{ matrix.target }}
      run: |
        case "${{ matrix.target }}" in
          arm-linux-gnueabi)
            CC=arm-linux-gnueabi-gcc
            OUTPUT=ptbl
            ;;
          arm-linux-gnueabihf)
            CC=arm-linux-gnueabihf-gcc
            OUTPUT=ptbl_hf
            ;;
          mips-unknown-linux-uclibc)
            CC=mips-linux-gnu-gcc
            OUTPUT=ptbl_mips
            ;;
        esac
        
        $CC -O2 -marm -Wall ptbl.c -ldl -o $OUTPUT -Wl,--export-dynamic
        echo "Checking binary type:"
        file $OUTPUT

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}-binary
        path: |
          ptbl
          ptbl_hf
          ptbl_mips
        if-no-files-found: error

  build-all:
    runs-on: ubuntu-22.04
    needs: build
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: *-binary
        merge-multiple: true

    - name: List built binaries
      run: |
        echo "Built binaries:"
        find artifacts -type f -executable -exec file {} \;
        echo "Copying to root..."
        cp artifacts/* ./
        ls -la ptbl* || true

    - name: Upload final binaries
      uses: actions/upload-artifact@v4
      with:
        name: final-binaries
        path: |
          ptbl
          ptbl_hf
          ptbl_mips
        if-no-files-found: warn
